#!/bin/sh
# Author: Salvador Zendejas


case "$1" in
    start)
        echo "Loading k-scull"
        scull_load
        ;;
    stop)
        echo "Unloading k-scull"
        scull_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0