#!/bin/sh
# Author: Salvador Zendejas


case "$1" in
    start)
        echo "Loading k-misc-modules"
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading k-misc-modules"
        module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0